# Generated by Django 5.0.6 on 2024-06-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('height', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('doctorname', models.CharField(max_length=100, null=True)),
                ('doctor_id', models.IntegerField()),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('health_concerns', models.CharField(max_length=100, null=True)),
                ('patient_id', models.CharField(max_length=100, null=True)),
                ('treatment', models.CharField(default='not', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_in_patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('height', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('health_concerns', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('doctor_email', models.CharField(max_length=255, unique=True)),
                ('doctor_password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_login_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('doctor_email', models.CharField(max_length=255)),
                ('doctor_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_registeration',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('doctor_first_name', models.CharField(max_length=255)),
                ('doctor_last_name', models.CharField(max_length=255)),
                ('doctor_specialization', models.CharField(max_length=255)),
                ('doctor_contact', models.CharField(max_length=14, unique=True)),
                ('doctor_profile_picture', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_upcoming_appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_time', models.TimeField(null=True)),
            ],
        ),
    ]
