# Generated by Django 5.0.6 on 2024-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Details_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('height', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('doctorname', models.CharField(max_length=100, null=True)),
                ('doctor_id', models.CharField(max_length=100, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('health_concerns', models.CharField(max_length=100, null=True)),
                ('patient_id', models.CharField(max_length=100, null=True)),
                ('treatment', models.CharField(default='not', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=10, unique=True)),
                ('patient_name', models.CharField(default='Null', max_length=100)),
                ('doctor_name', models.CharField(default='Null', max_length=100)),
                ('test_name', models.CharField(default='Null', max_length=100)),
                ('date', models.CharField(default='Null', max_length=100)),
                ('status', models.CharField(default='Null', max_length=20)),
                ('dofb', models.CharField(default='Null', max_length=50)),
                ('phone', models.CharField(default='Null', max_length=50)),
                ('gender', models.CharField(default='Null', max_length=50)),
                ('email', models.EmailField(default='Null', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment_Details',
        ),
        migrations.DeleteModel(
            name='doctor_login',
        ),
        migrations.DeleteModel(
            name='doctor_upcoming_appointments',
        ),
        migrations.RenameField(
            model_name='doctor_in_patients',
            old_name='dob',
            new_name='update_jdate',
        ),
        migrations.RenameField(
            model_name='doctor_in_patients',
            old_name='gender',
            new_name='update_pname',
        ),
        migrations.RenameField(
            model_name='doctor_in_patients',
            old_name='status',
            new_name='update_status',
        ),
        migrations.RemoveField(
            model_name='doctor_in_patients',
            name='health_concerns',
        ),
        migrations.RemoveField(
            model_name='doctor_in_patients',
            name='height',
        ),
        migrations.RemoveField(
            model_name='doctor_in_patients',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor_in_patients',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='doctor_registeration',
            name='doctor_contact',
        ),
        migrations.AddField(
            model_name='doctor_in_patients',
            name='update_history',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor_in_patients',
            name='update_med',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor_in_patients',
            name='update_note',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor_in_patients',
            name='update_plan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor_in_patients',
            name='update_symptoms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor_login_credentials',
            name='u_type',
            field=models.CharField(default='doctor', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor_registeration',
            name='doctor_dob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor_registeration',
            name='doctor_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor_in_patients',
            name='doctor_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_login_credentials',
            name='doctor_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_registeration',
            name='doctor_id',
            field=models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor_registeration',
            name='doctor_profile_picture',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
