# Generated by Django 4.2.5 on 2024-06-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_details',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
