# Generated by Django 5.0.6 on 2024-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('username', models.CharField(default='admin', max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default='admin', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('height', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('doctorname', models.CharField(max_length=100, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('health_concerns', models.CharField(max_length=100, null=True)),
                ('patient_id', models.CharField(max_length=100, null=True)),
                ('treatment', models.CharField(default='not', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('concern', models.CharField(max_length=100, null=True)),
                ('dname', models.CharField(max_length=100, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('slot_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otp_forget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, null=True)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, null=True)),
                ('bill', models.IntegerField()),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, null=True)),
                ('payment_amount', models.IntegerField()),
                ('status', models.CharField(max_length=100, null=True)),
                ('date_of_pay', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_Username', models.CharField(max_length=100, null=True)),
                ('tech_password', models.CharField(max_length=100, null=True)),
                ('tech_u_type', models.CharField(default='technician', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='patient_details',
            name='patient_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient_details',
            name='u_type',
            field=models.CharField(default='patient', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
